# Generated by Django 2.2.4 on 2020-05-09 09:26

from django.db import migrations

import phonenumbers


def normalize_phones(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        owners_phonenumber = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(owners_phonenumber):
            flat.owner_phone_pure = phonenumbers.format_number(
                owners_phonenumber,
                phonenumbers.PhoneNumberFormat.E164
            )
            flat.save()


def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owner_phone_pure = ''
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_flat_owner_phone_pure'),
    ]

    operations = [
        migrations.RunPython(normalize_phones, move_backward)
    ]
