# Generated by Django 2.2.4 on 2020-05-11 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20200511_2143'),
    ]

    operations = [
    ]
