# Generated by Django 2.2.4 on 2020-05-11 21:25

from django.db import migrations


def set_flats_to_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for owner in Owner.objects.all():
        Flat.objects


def move_backward(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    all_owners = Owner.objects.all()
    all_owners.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20200511_2223'),
    ]

    operations = [
        migrations.RunPython(set_flats_to_owners, move_backward)
    ]
