# Generated by Django 2.2.4 on 2020-05-12 11:01

from django.db import migrations


def set_flats_to_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for owner in Owner.objects.all():
        flats = Flat.objects.filter(
            owner=owner.full_name,
            owners_phonenumber=owner.owner_phonenumber,
            owner_phone_pure=owner.owner_phone_pure
        )
        owner.flats.set(flats)



def move_backward(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')

    for owner in Owner.objects.all():
        owner.flats.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20200512_1359'),
    ]

    operations = [
        migrations.RunPython(set_flats_to_owners, move_backward)
    ]
